-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 11:56:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(60) NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `telefone_cliente` VARCHAR(15) NOT NULL,
  `email_cliente` VARCHAR(60) NOT NULL,
  `cep_cliente` VARCHAR(8) NOT NULL,
  `endereco_cliente` VARCHAR(50) NULL,
  `data_nascimento_cliente` DATE NOT NULL,
  `sexo_cliente` ENUM("Masculino", "Feminino", "Outros") NULL,
  `genero_cliente` VARCHAR(30) NULL,
  `etnia_cliente` VARCHAR(30) NOT NULL,
  `nome_social_cliente` VARCHAR(60) NULL,
  `estado_civil_cliente` VARCHAR(30) NOT NULL,
  `data_cadastro_cliente` DATE NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`codigo_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `email_cliente_UNIQUE` (`email_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `codigo_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(30) NOT NULL,
  `categoria_produto` VARCHAR(30) NOT NULL,
  `descricao_produto` TEXT NOT NULL,
  `fabricante_produto` VARCHAR(30) NOT NULL,
  `marca_produto` VARCHAR(30) NOT NULL,
  `preco_produto` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`codigo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `codigo_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cpf_funcionario` VARCHAR(11) NOT NULL,
  `rg_funcionario` VARCHAR(11) NOT NULL,
  `certidao_nascimento_funcionario` VARCHAR(30) NULL,
  `certificado_reservista_funcionario` VARCHAR(12) NULL,
  `certidao_casamento_funcionario` VARCHAR(30) NULL,
  `titulo_eleitor_funcionario` VARCHAR(11) NULL,
  `telefone_funcionario` VARCHAR(15) NULL,
  `email_funcionario` VARCHAR(60) NOT NULL,
  `cep_funcionario` VARCHAR(8) NOT NULL,
  `endereco_funcionario` VARCHAR(60) NOT NULL,
  `data_nascimento_funcionario` DATE NOT NULL,
  `sexo_funcionario` ENUM("Masculino", "Feminino", "Outros") NULL,
  `genero_funcionario` VARCHAR(30) NULL,
  `etnia_funcionario` VARCHAR(30) NOT NULL,
  `nome_social_funcionario` VARCHAR(60) NULL,
  `estado_civil_funcionario` VARCHAR(30) NOT NULL,
  `data_admissao_funcionario` DATE NULL DEFAULT current_timestamp(),
  `data_demissao_funcionario` DATE NULL,
  `escolaridade_funcionario` ENUM("Fundamental", "Medio", "Graduacao", "Pos-Graduacao") NULL,
  `pis_funcionario` VARCHAR(11) NOT NULL,
  `carteira_trabalho_funcionario` VARCHAR(11) NOT NULL,
  `cargo_funcionario` VARCHAR(30) NOT NULL,
  `salario_funcionario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_funcionario`),
  UNIQUE INDEX `rg_funcionario_UNIQUE` (`rg_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_funcionario_UNIQUE` (`cpf_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `certidao_nascimento_funcionario_UNIQUE` (`certidao_nascimento_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `certificado_reservista_funcionario_UNIQUE` (`certificado_reservista_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `certidao_casamento_funcionario_UNIQUE` (`certidao_casamento_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `funcionariocol_UNIQUE` (`titulo_eleitor_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `telefone_funcionario_UNIQUE` (`telefone_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `email_funcionario_UNIQUE` (`email_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `pis_funcionario_UNIQUE` (`pis_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `funcionariocol_UNIQUE` (`carteira_trabalho_funcionario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `codigo_estoque` INT NOT NULL AUTO_INCREMENT,
  `codigo_produto` INT NOT NULL,
  `fabricacao_produto` DATE NOT NULL,
  `validade_produto` DATE NOT NULL,
  `lote_produto` VARCHAR(30) NOT NULL,
  `data_entrada_produto` DATE NULL DEFAULT default current_timestamp,
  `quantidade_entrada_produto` INT NOT NULL DEFAULT 1,
  `quantidade_atual_produto` INT NOT NULL,
  `setor_produto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo_estoque`),
  UNIQUE INDEX `lote_produto_UNIQUE` (`lote_produto` ASC) VISIBLE,
  INDEX `fk_estoque_produto_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `codigo_venda` INT NULL AUTO_INCREMENT,
  `codigo_cliente` INT NOT NULL,
  `codigo_funcionario` INT NOT NULL,
  `data_hora_venda` DATETIME NULL DEFAULT default current_timestamp(),
  `total_venda` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_venda`),
  INDEX `fk_Venda_funcionario1_idx` (`codigo_funcionario` ASC) VISIBLE,
  INDEX `fk_Venda_cliente1_idx` (`codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_funcionario1`
    FOREIGN KEY (`codigo_funcionario`)
    REFERENCES `mydb`.`funcionario` (`codigo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_cliente1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `mydb`.`cliente` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Itens da Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Itens da Venda` (
  `codigo_itens_venda` INT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  `desconto_venda` DECIMAL(4,2) NULL DEFAULT 0.0,
  `quantidade` INT NOT NULL DEFAULT 1,
  `subtotal` DECIMAL(7,2) NULL,
  PRIMARY KEY (`codigo_itens_venda`),
  INDEX `fk_Itens da Venda_Venda1_idx` (`codigo_venda` ASC) VISIBLE,
  INDEX `fk_Itens da Venda_produto1_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Itens da Venda_Venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`Venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens da Venda_produto1`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `codigo_pagamento` INT NOT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `forma_pagamento` ENUM("Pix", "Débito", "Crédito", "Dinheiro", "Voucher") NOT NULL,
  `informacao_cartao` VARCHAR(255) NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `valor_recebido` DECIMAL(5,2) NOT NULL,
  `troco` DECIMAL(4,2) NULL,
  `numero_parcelas` INT NOT NULL DEFAULT 1,
  `valor_parcela` DECIMAL(7,2) NULL,
  `status_pagamento` ENUM("Pendente", "Aprovado", "Recusado") NULL DEFAULT 'defautl \"Pendente\"',
  PRIMARY KEY (`codigo_pagamento`),
  INDEX `fk_Pagamento_Venda1_idx` (`codigo_venda` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`Venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
